{{- if .Values.keyVaultSecrets.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "afga-agent.fullname" . }}-secrets
  labels:
    {{- include "afga-agent.labels" . | nindent 4 }}
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: {{ .Values.keyVaultSecrets.clientId | quote }}
    keyvaultName: {{ .Values.keyVaultSecrets.vaultName | quote }}
    tenantId: {{ .Values.keyVaultSecrets.tenantId | quote }}
    objects: |
      array:
        {{- range .Values.keyVaultSecrets.objects }}
        - |
          objectName: {{ .objectName }}
          objectType: {{ .objectType }}
          {{- if .objectFormat }}
          objectFormat: {{ .objectFormat }}
          {{- end }}
          {{- if .objectEncoding }}
          objectEncoding: {{ .objectEncoding }}
          {{- end }}
        {{- end }}
    {{- if .Values.keyVaultSecrets.tenantId }}
    tenantId: {{ .Values.keyVaultSecrets.tenantId | quote }}
    {{- end }}
  secretObjects:
    {{- range .Values.keyVaultSecrets.objects }}
    - secretName: {{ $.Values.keyVaultSecrets.vaultName }}-{{ .objectName }}
      type: Opaque
      data:
        - key: {{ .objectName }}
          objectName: {{ .objectName }}
    {{- end }}
{{- end }}

